// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0JilcNVd1bKQWHqtEpHRKc1wmZzGVGA',
    appId: '1:195577296612:web:a019d2b5ff9d5629655ef1',
    messagingSenderId: '195577296612',
    projectId: 'todolist-e207',
    authDomain: 'todolist-e207.firebaseapp.com',
    storageBucket: 'todolist-e207.appspot.com',
    measurementId: 'G-MV1C5ZQDB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP6Jpno2LvYXT40U8veMjPlxvnJemitck',
    appId: '1:195577296612:android:c89f1878b46a91bb655ef1',
    messagingSenderId: '195577296612',
    projectId: 'todolist-e207',
    storageBucket: 'todolist-e207.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8oaoqAlrKX1sMcIlkt4ycsCQpD3ZAhAQ',
    appId: '1:195577296612:ios:441eba50e1f2974b655ef1',
    messagingSenderId: '195577296612',
    projectId: 'todolist-e207',
    storageBucket: 'todolist-e207.appspot.com',
    iosBundleId: 'com.example.todoUsermary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8oaoqAlrKX1sMcIlkt4ycsCQpD3ZAhAQ',
    appId: '1:195577296612:ios:441eba50e1f2974b655ef1',
    messagingSenderId: '195577296612',
    projectId: 'todolist-e207',
    storageBucket: 'todolist-e207.appspot.com',
    iosBundleId: 'com.example.todoUsermary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0JilcNVd1bKQWHqtEpHRKc1wmZzGVGA',
    appId: '1:195577296612:web:a38342db5a70e473655ef1',
    messagingSenderId: '195577296612',
    projectId: 'todolist-e207',
    authDomain: 'todolist-e207.firebaseapp.com',
    storageBucket: 'todolist-e207.appspot.com',
    measurementId: 'G-68HXT2FT1J',
  );

}