name: Flutter CI

on:
  push:
    branches: [ "main", "fourth-phase" ]
  pull_request:
    branches: [ "main", "fourth-phase" ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

  setup_flutter:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

  verify_formatting:
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Verify formatting
        run: dart format --output=none

  run_linter:
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Run linter
        run: flutter analyze
        continue-on-error: true

  run_tests:
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Run tests
        run: flutter test
        continue-on-error: true

  setup_java:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

  build_apk:
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Build apk
        run: flutter build apk

  upload_apk:
    runs-on: ubuntu-latest
    needs: [setup_java, build_apk]
    steps:
      - name: Upload apk to Firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-release.apk